- name: conditions
  hosts: localhost
  tasks:
    - name: Welcome to Devops class
      ansible.builtin.debug:
        msg: Welcome to Devops class
      when: course_name == 'Devops' OR course_name == 'devops'

    - name: Welcome to Ansible class
      ansible.builtin.debug:
        msg: Welcome to Ansible class
      when: course_name == 'Ansible'