- name: loops
  hosts: localhost
  tasks:
    - name: Print numbers
      ansible.builtin.debug:
        msg: " {{ item }} "
      loop:
        - apple
        - banana

    - name: print course
      ansible.builtin.debug:
        msg: Course name is {{ item["course_name"] }} and course duration is {{ item["course_duration"] }}
      loop:
        - { course_name: 'Devops', course_duration: 3 }
        - { course_name: 'Ansible', course_duration: 2 }
