- name: variables
  hosts: localhost
  vars:
    URL: aditya.google.com
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: URL - {{ URL }}

    - name: Print fruit names
      ansible.builtin.debug:
        msg: Fruit name is - {{ FRUIT }}
      vars:
        FRUIT:
          - apple
          - pineapple
          - orange