- name: variables
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    URL: aditya.google.com
    STRING: aditya
    BOOL: true
    NUMBER: 1
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: URL - {{ URL }}

    - name: Print fruit names
      ansible.builtin.debug:
        msg: Fruit name is - {{ FRUIT }}
      vars:
        FRUIT: apple

    - name: Print project Name
      ansible.builtin.debug:
        msg: "{{ PROJECT_NAME }}"
      vars:
          PROJECT_NAME: Ansible

    - name: list of fruits
      ansible.builtin.debug:
        msg: List of fruits is {{ FRUITS[1] }}
      vars:
        FRUITS:
          - apple
          - orange
          - banana
          - grapes

    - name: list of fruits using map
      ansible.builtin.debug:
        msg: List of fruits is {{ FRUITS_MAP['key1'] }}
      vars:
        FRUITS_MAP:
          key1: apple
          key2: orange
          key3: banana
          key4: grapes

